language: ruby
rvm:
- 2.6.5

script:
  - bundle exec rspec
  - bundle exec rubocop
# after_script:
# - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT # Upload coverage/codeclimate.json